export default {
    addmoney:'addmoney',
    showrubbish:'ShowRubbish',
    hiderubbish:'HideRubbish',
    sell:'Sell',
    nextlevel:'nextLevel',
    gameover:'GameOver',
    //初始塔等级改变
    initchange:'InitChange',
    //显示大大的group字样
    showGroupLabel:'ShowGroupLabel',
    //显示大大的round字样
    showRoundLabel:'ShowRoundLabel',
    //显示大大的Fail字样
    showFailLabel:'ShowFailLabel',
    //改变关卡
    stageChange:'StageChange',
    //itemLayer震动
    itemLayervibrate:'ItemLayervibrate',
}